export {AuthPageWrapperComponent} from './auth.component'
export {LoginPageComponent} from './login-page/login-page.component'
export {RegisterPageComponent} from './register-page/register-page.component'
export {VerifyPageComponent} from './verify-page/verify-page.component'
export {RecoveryPageComponent} from './recovery-page/recovery-page.component'
export {ErrorPageComponent} from './error-page/error-page.component'
