auth:
  port: 8000

project:
  port: 8001

org:
  port: 8002

app:
  secret_key: "WRP+0Fs&@&KXiNS8>gV4_(;>4w]Ce*[ClJsa6MXXG+^t.2M[u+.7JD$FPd9[Jn#;J*5.plAy{z|Um{UV7N;bTb;S%l45Sz^2Jt#raxF9060YIFeYlKpz"

db:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432

email:
  host: "smtp.gmail.com"
  port: 587
  user: "google user email"
  pass: "app_secret"
  from: "shanin.x@gmail.com"
  tls: true
  smtp: "smtps://test:test@mailslurper:1025/?skip_ssl_verify=true"

kratos:
  url_admin: "http://localhost:4434"
  url_browser: "http://localhost:4433"
