- id: "auth-service"
  upstream:
    preserve_host: true
    url: "http://localhost:8000"
  match:
    url: "http://localhost:8080/api/auth/<**>"
    methods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
  authenticators:
    - handler: noop
  mutators:
    - handler: noop
  authorizer:
    handler: allow
